import Navbar from './Navbar';
import Sidebar from './Sidebar';
import Footer from './Footer';
import FeaturedCoins from './FeaturedCoins';
import CoinsFilters from './CoinsFilters';
import ExtraFilters from './ExtraFilters';
import CoinsSort from './CoinsSort';
import CoinsList from './CoinsList';
import CoinsPagination from './CoinsPagination';
import Loader from './Loader';
import PageHero from './PageHero';
import CoinsTable from './CoinsTable';
import FeaturedExchanges from './FeaturedExchanges';
import ExchangesTable from './ExchangesTable';
import ExchangesFilters from './ExchangesFilters';
import ExchangesSort from './ExchangesSort';
import ExchangesList from './ExchangesList';
import ExchangesPagination from './ExchangesPagination';

export { Navbar, Sidebar, Footer, FeaturedCoins, CoinsFilters, ExtraFilters, CoinsSort, CoinsList, CoinsPagination, Loader, PageHero, CoinsTable, ExchangesTable, FeaturedExchanges, ExchangesFilters, ExchangesSort, ExchangesList, ExchangesPagination };
